# Generated by Django 3.0.2 on 2020-01-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200115_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='todos.Tag'),
        ),
    ]
