# Generated by Django 3.0.2 on 2020-01-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20200109_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tag',
            new_name='tags',
        ),
    ]
