# Generated by Django 2.2.9 on 2020-04-20 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20200121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
