# Generated by Django 3.0.2 on 2020-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='created_at',
        ),
    ]
