# Generated by Django 3.0.2 on 2020-01-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todos.Project'),
        ),
    ]
